import type { Metadata } from "next";
import "./globals.css";
import "bootswatch/dist/sketchy/bootstrap.min.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="pt-2 px-4">
          <Navbar />
          <div className=" mt-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
